import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "highlight.js/styles/github.css";
import "highlight.js/styles/atom-one-dark.css";
// import "highlight.js/styles/nord.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CSC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-background " // 新增：应用背景色到根元素
      // className="dark"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
        style={{ margin: 0, padding: 0 }} // 新增：确保 body 背景覆盖
      >
        {children}
      </body>
    </html>
  );
}
